name: austere
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.9
  cloud_firestore:
  firebase_storage:
  image_picker: ^0.8.7+3
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
 # firebase_messaging: ^15.2.5
  # flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Inter_24pt
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf

dependency_overrides:
  material_color_utilities: ^0.12.0
  vector_math: ^2.1.5